= spring gateway 取代 nginx

最近学了 spring gateway，之前都是使用 nginx 作为反向代理服务器，但 nginx 对于笔者来说配置起来比较生疏，现在有了 spring gateway，也可以进行反向代理，作为 java 程序员，配置起来更顺手，所以自然而然地想要用 spring gateway 替换掉 nginx。

//目前实际使用经验比较少，后续不断补充内容。

== 创建 spring gateway 项目

创建 spring gateway 的项目，简单地添加依赖 `org.springframework.cloud:spring-cloud-starter-gateway:2.3.0.RELEASE` 后启动运行。

如果执行单元测试需要添加依赖 `testImplementation 'org.springframework.boot:spring-boot-starter-validation'`，否则会报错，具体原因待分析。
//TODO 了解具体原因

== 代理动态资源

spring gateway 提供了非常方便的配置，可以实现动态资源的转发和重定向，以下简单地配置转发：

[source%nowrap,yml]
----
spring:
  cloud:
    gateway:
      routes:
        - id: peacetrue-microservice-resource-server
          uri: lb://peacetrue-microservice-resource-server
          predicates:
            - Path=/resource-server/**
        - id: peacetrue-region
          uri: lb://peacetrue-region
          predicates:
            - Path=/regions/**
        - id: peacetrue-user
          uri: lb://peacetrue-user
          predicates:
            - Path=/users/**
        - id: peacetrue-attachment
          uri: lb://peacetrue-attachment
          predicates:
            - Path=/attachments/**
----

想要了解更多用法参考 待定。
//TODO 提供网关文章

== 代理静态资源

代理动态资源很容易，但对于静态资源目前只能在代码中声明：

[source%nowrap,java]
----
@Bean
public RouterFunction<ServerResponse> staticResourceLocator() {
        return RouterFunctions.resources("/static/**", new FileSystemResource("/Users/peacetrue/static/"));
}
----

上面的示例，路径以 /static/ 起始的静态资源，会从物理路径 /Users/peacetrue/static/ 下读取，例如：请求 https://peacetrue.cn/static/index.html 会匹配 /Users/peacetrue/static/index.html 文件。

=== 配置化支持

只能在代码中声明比较繁琐，简单地实现从配置读取：

.StaticResourceProperties
[source%nowrap,java]
----
@Data
@ConfigurationProperties("peacetrue")
public class StaticResourceProperties {
    /** 静态资源配置，key 表示路径规则，value 表示转发地址 */
    private Map<String, String> staticResources = new LinkedHashMap<>();
}

----

.StaticResourceAutoConfiguration
[source%nowrap,java]
----
@Slf4j
@Configuration
@EnableConfigurationProperties(StaticResourceProperties.class)
public class StaticResourceAutoConfiguration {

    private StaticResourceProperties properties;

    public StaticResourceAutoConfiguration(StaticResourceProperties properties) {
        this.properties = properties;
    }

    @Bean
    @ConditionalOnMissingBean(name = "staticResources")
    public Map<String, String> staticResources() {
        return properties.getStaticResources();
    }

    @Bean
    @ConditionalOnBean(name = "staticResources", value = Map.class)
    public RouterFunction<ServerResponse> staticResourceLocator(ResourceLoader resourceLoader,
                                                                Map<String, String> staticResources) {
        if (staticResources.isEmpty()) return null;//<1>
        RouterFunctions.Builder builder = RouterFunctions.route();
        staticResources.forEach((key, value) -> {
            log.debug("添加静态资源配置: [{}] -> [{}]", key, value);
            builder.add(RouterFunctions.resources(key, resourceLoader.getResource(value)));
        });
        return builder.build();
    }

}
----
<1> 空 `Map` 其实不需要启用配置，但没有 `@ConditionalOnNotEmptyBean` 这种注解， https://stackoverflow.com/questions/62734544/spring-conditionalonproperty-for-bean[此问题^] 待优化

//TODO 此问题待优化

.配置示例
[source%nowrap,yml]
----
peacetrue:
  static-resources:
    '[/test/**]': file:/Users/xiayx/Documents/Projects/peacetrue-microservice/docs/antora/modules/ROOT/pages/ //<1>
    '[/summarize/**]': file:/root/peacetrue/document-antora/public/ //<2>
    '[/classpath/**]': classpath:public/ //<3>
----
<1> 路径需要转译
<2> 配置物理路径地址
<3> 配置类路径地址
